// packages/vue/src/assets/MoreOne.tsx
import React from 'react';
import { VNode } from 'vue';
import { ISvgIconProps, IconHelper, SvgIconWrapper } from '../components';

export default SvgIconWrapper('more-one', false, (h: IconHelper, props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
        <circle cx="24" cy="12" r="3" fill={props.colors[0]} />
        <circle cx="24" cy="24" r="3" fill={props.colors[0]} />
        <circle cx="24" cy="35" r="3" fill={props.colors[0]} />
    </svg>
)  as any as VNode);

// packages/react/src/assets/MoreOne.tsx
import React from 'react';
import { ISvgIconProps, SvgIconWrapper } from '../components';

export default SvgIconWrapper('more-one', false, (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
        <circle fill={props.colors[1]} r="3" cy="12" cx="24" />
        <circle fill={props.colors[1]} r="3" cy="24" cx="24" />
        <circle fill={props.colors[1]} r="3" cy="35" cx="24" />
    </svg>
));
