// packages/react/src/assets/Cpu.tsx
import React from 'react';
import { ISvgIconProps, SvgIconWrapper } from '../components';

export default SvgIconWrapper('cpu', false, (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
        <path
            d="M38 8H10C8.89543 8 8 8.89543 8 10V38C8 39.1046 8.89543 40 10 40H38C39.1046 40 40 39.1046 40 38V10C40 8.89543 39.1046 8 38 8Z"
            fill={props.colors[1]}
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            d="M30 18H18V30H30V18Z"
            fill={props.colors[3]}
            stroke={props.colors[2]}
            strokeWidth={props.strokeWidth}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M14.9092 2V8V2Z"
            fill={props.colors[1]}
        />
        <path
            d="M14.9092 2V8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M14.9092 40V46V40Z"
            fill={props.colors[1]}
        />
        <path
            d="M14.9092 40V46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M24 2V8V2Z"
            fill={props.colors[1]}
        />
        <path
            d="M24 2V8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M24 40V46V40Z"
            fill={props.colors[1]}
        />
        <path
            d="M24 40V46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M33.0908 2V8V2Z"
            fill={props.colors[1]}
        />
        <path
            d="M33.0908 2V8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M33.0908 40V46V40Z"
            fill={props.colors[1]}
        />
        <path
            d="M33.0908 40V46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 14.9092H8H2Z"
            fill={props.colors[1]}
        />
        <path
            d="M2 14.9092H8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M40 14.9092H46H40Z"
            fill={props.colors[1]}
        />
        <path
            d="M40 14.9092H46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 24H8H2Z"
            fill={props.colors[1]}
        />
        <path
            d="M2 24H8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M40 24H46H40Z"
            fill={props.colors[1]}
        />
        <path
            d="M40 24H46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 33.0908H8H2Z"
            fill={props.colors[1]}
        />
        <path
            d="M2 33.0908H8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M40 33.0908H46H40Z"
            fill={props.colors[1]}
        />
        <path
            d="M40 33.0908H46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
    </svg>
));

// packages/vue/src/assets/Cpu.tsx
import React from 'react';
import { VNode } from 'vue';
import { ISvgIconProps, IconHelper, SvgIconWrapper } from '../components';

export default SvgIconWrapper('cpu', false, (h: IconHelper, props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
        <path
            d="M38 8H10C8.89543 8 8 8.89543 8 10V38C8 39.1046 8.89543 40 10 40H38C39.1046 40 40 39.1046 40 38V10C40 8.89543 39.1046 8 38 8Z"
            fill={props.colors[1]}
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            d="M30 18H18V30H30V18Z"
            fill={props.colors[3]}
            stroke={props.colors[2]}
            strokeWidth={props.strokeWidth}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M14.9092 2V8V2Z"
            fill={props.colors[1]}
        />
        <path
            d="M14.9092 2V8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M14.9092 40V46V40Z"
            fill={props.colors[1]}
        />
        <path
            d="M14.9092 40V46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M24 2V8V2Z"
            fill={props.colors[1]}
        />
        <path
            d="M24 2V8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M24 40V46V40Z"
            fill={props.colors[1]}
        />
        <path
            d="M24 40V46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M33.0908 2V8V2Z"
            fill={props.colors[1]}
        />
        <path
            d="M33.0908 2V8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M33.0908 40V46V40Z"
            fill={props.colors[1]}
        />
        <path
            d="M33.0908 40V46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 14.9092H8H2Z"
            fill={props.colors[1]}
        />
        <path
            d="M2 14.9092H8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M40 14.9092H46H40Z"
            fill={props.colors[1]}
        />
        <path
            d="M40 14.9092H46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 24H8H2Z"
            fill={props.colors[1]}
        />
        <path
            d="M2 24H8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M40 24H46H40Z"
            fill={props.colors[1]}
        />
        <path
            d="M40 24H46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M2 33.0908H8H2Z"
            fill={props.colors[1]}
        />
        <path
            d="M2 33.0908H8"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M40 33.0908H46H40Z"
            fill={props.colors[1]}
        />
        <path
            d="M40 33.0908H46"
            stroke={props.colors[0]}
            strokeWidth={props.strokeWidth}
            strokeLinecap={props.strokeLinecap}
            strokeLinejoin={props.strokeLinejoin}
        />
    </svg>
)  as any as VNode);
