// packages/react/src/assets/More.tsx
import React from 'react';
import { ISvgIconProps, SvgIconWrapper } from '../components';

export default SvgIconWrapper('more', false, (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
        <circle fill={props.colors[1]} r="3" cy="24" cx="12" />
        <circle fill={props.colors[1]} r="3" cy="24" cx="24" />
        <circle fill={props.colors[1]} r="3" cy="24" cx="36" />
    </svg>
));

// packages/vue/src/assets/More.tsx
import React from 'react';
import { VNode } from 'vue';
import { ISvgIconProps, IconHelper, SvgIconWrapper } from '../components';

export default SvgIconWrapper('more', false, (h: IconHelper, props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
        <circle cx="12" cy="24" r="3" fill={props.colors[0]} />
        <circle cx="24" cy="24" r="3" fill={props.colors[0]} />
        <circle cx="36" cy="24" r="3" fill={props.colors[0]} />
    </svg>
)  as any as VNode);
